### ISSUE TITLE
Document that pkg-config is necessary to build gem

### ISSUE THREAD

**Issue by luke-gru** [aycabta/vterm-gem#10]
It's not immediately obvious that this is needed, I needed to take a look at extconf.rb when the native extension was not getting built properly.

**Comment by yutakusuno** [comment]
I needed to take a look at `extconf.rb` when I was setting up the development environment for [reline]( https://github.com/ruby/reline) as well.

- macOS Ventura 13.4 (M1 chip)
- `libvterm` is installed (As this procedure [here](https://github.com/ruby/reline#run-tests))

Executing `WITH_VTERM=1 bundle install`,  causes BuildError.

```
Fetching https://github.com/ruby/yamatanooroti.git
Fetching https://github.com/ruby/vterm-gem.git
Fetching gem metadata from https://rubygems.org/.......
Resolving dependencies...
Fetching rake 13.0.6
Installing rake 13.0.6
Using bundler 2.4.6
Using io-console 0.6.0
Fetching power_assert 2.0.3
Using reline 0.3.5 from source at `.`
Using vterm 0.0.5 from https://github.com/ruby/vterm-gem.git (at master@ab90c9c)
Installing power_assert 2.0.3
Fetching test-unit 3.6.0
Installing test-unit 3.6.0
Using yamatanooroti 0.0.9 from https://github.com/ruby/yamatanooroti.git (at master@9eb1577)
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /Users/yutakusuno/Repositories/oss/reline/vendor/bundle/ruby/3.2.0/bundler/gems/vterm-gem-ab90c9c1b42f/ext/vterm
/Users/yutakusuno/.asdf/installs/ruby/3.2.1/bin/ruby -I /Users/yutakusuno/.asdf/installs/ruby/3.2.1/lib/ruby/3.2.0 extconf.rb
checking for vterm.h... no
checking for vterm_new() in -lvterm... no
creating Makefile

current directory: /Users/yutakusuno/Repositories/oss/reline/vendor/bundle/ruby/3.2.0/bundler/gems/vterm-gem-ab90c9c1b42f/ext/vterm
make DESTDIR\= sitearchdir\=./.gem.20230610-75536-6byu48 sitelibdir\=./.gem.20230610-75536-6byu48 clean

current directory: /Users/yutakusuno/Repositories/oss/reline/vendor/bundle/ruby/3.2.0/bundler/gems/vterm-gem-ab90c9c1b42f/ext/vterm
make DESTDIR\= sitearchdir\=./.gem.20230610-75536-6byu48 sitelibdir\=./.gem.20230610-75536-6byu48
compiling vterm.c
vterm.c:10:10: fatal error: 'vterm.h' file not found
#include "vterm.h"
         ^~~~~~~~~
1 error generated.
make: *** [vterm.o] Error 1

make failed, exit code 2

Gem files will remain installed in /Users/yutakusuno/Repositories/oss/reline/vendor/bundle/ruby/3.2.0/bundler/gems/vterm-gem-ab90c9c1b42f for inspection.
Results logged to /Users/yutakusuno/Repositories/oss/reline/vendor/bundle/ruby/3.2.0/bundler/gems/extensions/arm64-darwin-22/3.2.0/vterm-gem-ab90c9c1b42f/gem_make.out

  /Users/yutakusuno/.asdf/installs/ruby/3.2.1/lib/ruby/3.2.0/rubygems/ext/builder.rb:102:in `run'
  /Users/yutakusuno/.asdf/installs/ruby/3.2.1/lib/ruby/3.2.0/rubygems/ext/builder.rb:51:in `block in make'
  /Users/yutakusuno/.asdf/installs/ruby/3.2.1/lib/ruby/3.2.0/rubygems/ext/builder.rb:43:in `each'
  /Users/yutakusuno/.asdf/installs/ruby/3.2.1/lib/ruby/3.2.0/rubygems/ext/builder.rb:43:in `make'
  /Users/yutakusuno/.asdf/installs/ruby/3.2.1/lib/ruby/3.2.0/rubygems/ext/ext_conf_builder.rb:42:in `build'
  /Users/yutakusuno/.asdf/installs/ruby/3.2.1/lib/ruby/3.2.0/rubygems/ext/builder.rb:170:in `build_extension'
  /Users/yutakusuno/.asdf/installs/ruby/3.2.1/lib/ruby/3.2.0/rubygems/ext/builder.rb:204:in `block in build_extensions'
  /Users/yutakusuno/.asdf/installs/ruby/3.2.1/lib/ruby/3.2.0/rubygems/ext/builder.rb:201:in `each'
  /Users/yutakusuno/.asdf/installs/ruby/3.2.1/lib/ruby/3.2.0/rubygems/ext/builder.rb:201:in `build_extensions'
  /Users/yutakusuno/.asdf/installs/ruby/3.2.1/lib/ruby/3.2.0/rubygems/installer.rb:843:in `build_extensions'
  /Users/yutakusuno/.asdf/installs/ruby/3.2.1/lib/ruby/3.2.0/bundler/rubygems_gem_installer.rb:72:in `build_extensions'
  /Users/yutakusuno/.asdf/installs/ruby/3.2.1/lib/ruby/3.2.0/bundler/source/path/installer.rb:28:in `post_install'
  /Users/yutakusuno/.asdf/installs/ruby/3.2.1/lib/ruby/3.2.0/bundler/source/path.rb:244:in `generate_bin'
  /Users/yutakusuno/.asdf/installs/ruby/3.2.1/lib/ruby/3.2.0/bundler/source/git.rb:188:in `install'
  /Users/yutakusuno/.asdf/installs/ruby/3.2.1/lib/ruby/3.2.0/bundler/installer/gem_installer.rb:54:in `install'
  /Users/yutakusuno/.asdf/installs/ruby/3.2.1/lib/ruby/3.2.0/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /Users/yutakusuno/.asdf/installs/ruby/3.2.1/lib/ruby/3.2.0/bundler/installer/parallel_installer.rb:155:in `do_install'
  /Users/yutakusuno/.asdf/installs/ruby/3.2.1/lib/ruby/3.2.0/bundler/installer/parallel_installer.rb:146:in `block in worker_pool'
  /Users/yutakusuno/.asdf/installs/ruby/3.2.1/lib/ruby/3.2.0/bundler/worker.rb:62:in `apply_func'
  /Users/yutakusuno/.asdf/installs/ruby/3.2.1/lib/ruby/3.2.0/bundler/worker.rb:57:in `block in process_queue'
  /Users/yutakusuno/.asdf/installs/ruby/3.2.1/lib/ruby/3.2.0/bundler/worker.rb:54:in `loop'
  /Users/yutakusuno/.asdf/installs/ruby/3.2.1/lib/ruby/3.2.0/bundler/worker.rb:54:in `process_queue'
  /Users/yutakusuno/.asdf/installs/ruby/3.2.1/lib/ruby/3.2.0/bundler/worker.rb:90:in `block (2 levels) in create_threads'

An error occurred while installing vterm (0.0.5), and Bundler cannot continue.

In Gemfile:
  vterm
```

But after `brew install pkg-config` and I re-run it., it worked.
